//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GVOne
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLoan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblLoan()
        {
            this.tblUserLoans = new HashSet<tblUserLoan>();
        }
    
        public long tblLoanID { get; set; }
        public string ActualLoanID { get; set; }
        public Nullable<long> PrimaryBorrowerID { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<long> tblLoanStatusID { get; set; }
        public Nullable<System.DateTime> ModifiedAt { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual tblLoanStatu tblLoanStatu { get; set; }
        public virtual tblUser tblUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUserLoan> tblUserLoans { get; set; }
    }
}
