//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GVOne
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSetting
    {
        public long tblSettingsID { get; set; }
        public Nullable<long> tblUserID { get; set; }
        public Nullable<bool> IsAllSettingEnable { get; set; }
        public Nullable<bool> IsPushNotificationEnable { get; set; }
        public Nullable<bool> IsAlertNotificationEnable { get; set; }
    
        public virtual tblUser tblUser { get; set; }
    }
}
