//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GVOne
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserLoan
    {
        public long tblLoanID { get; set; }
        public long tblUserID { get; set; }
        public long tblRoleID { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual tblLoan tblLoan { get; set; }
        public virtual tblRole tblRole { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
