//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GVOne
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserAlert
    {
        public long tblUserID { get; set; }
        public long tblAlertID { get; set; }
        public Nullable<bool> IsRead { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual tblAlert tblAlert { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
